### ISSUE TITLE
Protocol env var named wrong in mattermost.conf

### ISSUE THREAD

**Issue by ukk000** [neuland/matterminder#2]
Currently: `protocol=${?MATTERMINDER_PROTOCOL}`

Should be (according to README): `protocol=${?MATTERMINDER_MATTERMOST_PROTOCOL}`

https://github.com/neuland/matterminder/blob/9e03baaf5d0cd5478a858f9a8bdf558aea861c8b/conf/mattermost.conf#L2

**Comment by SebastianNieke** [comment]
You are absolutely right, I fixed it in 0279d0a2b815e82311f41c059a1c7c98b268fc60.
